#### LOG
quarkus.log.level=INFO

### HOST
quarkus.http.port=8080
quarkus.http.root-path=/golden-raspberry-awards/api

quarkus.datasource.db-kind=h2
quarkus.datasource.jdbc.url=jdbc:h2:mem:movielist;DB_CLOSE_DELAY=-1
#quarkus.datasource.jdbc.url=jdbc:h2:file:./data/movielist;DB_CLOSE_DELAY=-1
quarkus.datasource.username=sa
quarkus.datasource.password=sa

quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=false

app.csv.file-name=Movielist.csv

quarkus.swagger-ui.always-include=true
quarkus.smallrye-openapi.info-title=Golden Raspberry Awards API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.smallrye-openapi.info-description=API para consulta dos vencedores do Golden Raspberry Awards

%test.quarkus.test.rest-assured.enable-logging-on-failure=true

%dev.quarkus.datasource.dev-ui.allow-sql=true
